[package]
name = "orca-swap-oracle"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.9.20"
solana-client = "1.9.20"
solana-program = "1.9.20"

spl-token = "3.3.0"
spl-token-swap = "2.1.0"

serde = { version="1.0.137", features=["derive"] }

decimal = "2.1.0"
